### ISSUE TITLE
RubyHW1 feedback

### ISSUE THREAD

**Issue by LVALL** [Haidamac/RubyHW#1]
Insane level of work, really appreciate you've done all the tasks) 

All the solutions are nicely done and that's really good job!

I've checked probable solutions for task 64, where you solved the task with custom solution, and here is my suggestion:
```

p '64. Дано цілочисельний масив. Знайти максимальну кількість максимальних елементів, що йдуть підряд.'
p '[15, 99, 99, 99, -94, 14, 15, 99, 99, 38, -14, 17, 25, 99, 99, 99, 99]'
p array.each_index.select { |i| array[i] == array.max }.slice_when { |prev, curr| curr != prev.next }.to_a.map(&:size).max
```

you can play around to figure how it works) also is possible to use `inject([])` with some conditions, but I believe that `slice_when` is easier to understand

**Comment by Haidamac** [comment]
Thank you very much!
Special thanks for #64 suggestion!

**Comment by Haidamac** [comment]
I've understood how these methods work, thanks!
