### ISSUE TITLE
Feedback HW 7

### ISSUE THREAD

**Issue by LVALL** [Haidamac/RubyHW#10]
З пункту 1 в завданні все виконано коректно, єдиний момент - назва суміжної моделі 'Articletag', коректною була б назва 'ArticleTag' та таблиця 'article_tags'.

- [x] `Додати скоуп, щоб можна було отримати 10 останніх коментів для конкретного Article` не бачу даного скоупу для моделі `Comment`

- [x] для створення лайків варто продумати оптимальніший спосіб створення, ніж робити це з `if else`. (hint: для створення лайку нам достатньо передати `likeable_id`, `likeable_type`, `author_id`)

- [x] не забувайте прибирати зайві відступи та порожні строки, як [тут](https://github.com/Haidamac/RubyHW/blob/96c63c73a98a7ea28dbcc164af56f69005e14077/HW7/app/controllers/api/v1/likes_controller.rb#L13) і [тут](https://github.com/Haidamac/RubyHW/blob/96c63c73a98a7ea28dbcc164af56f69005e14077/HW7/app/controllers/api/v1/likes_controller.rb#L27)

- [x] завжди опрацьовуйте як позитивний, так і негативний кейси в методах, де відбувається зміна даних. У методі `destroy` контролеру `Api::V1::LikesController` буде виводитись повідомлення про відміну лайку, навіть, якшо destroy не спрацює. Також не забувайте про статуси для респонзів 

`render json: { message: 'Unliked' }, status: :no_content`

**Comment by Haidamac** [comment]
Дякую!
Всі зауваження врахував!!!
