### ISSUE TITLE
Фідбек ДЗ 6

### ISSUE THREAD

**Issue by Kashoid23** [Haidamac/RubyHW#11]
Хороша робота, кілька коментарів для допрацювання

- [x] В кожному наступному ДЗ починаючи з цього, додавайте гем рубокоп (https://github.com/rubocop/rubocop). І перевіряйте свій код в процесі та перед відправкою (команда в консолі - `rubocop`, або `rubocop -a` якщо хочете, щоб рубокоп сам застосував автоформатування коду). Так ви наочно побачите скільки у вас є з форматуванням виправлень.
- [x] Якщо ви не плануєте щось робити в середині блока (do end), то й відкривати (оголошувати) його не варто. Наприклад в routes.rb
https://github.com/Haidamac/RubyHW/blob/main/HW6/config/routes.rb#L7
https://github.com/Haidamac/RubyHW/blob/main/HW6/config/routes.rb#L4
вистачило б
```
resources :authors
....
resources :comments
```
- [x] Щоб дістати всі записи https://github.com/Haidamac/RubyHW/blob/main/HW6/app/models/comment.rb#L8
достатньо викликати метод `.all` https://apidock.com/rails/ActiveRecord/Scoping/Named/ClassMethods/all
В данному випадку, ви просто сортуєте записи, отже і скоуп повинен мати відповідну назву, наприклад `recent` або `newest`, залежно від сортування по даті
- [x] Потрібно додати асоціації між Article та Author відповідно до задачі
`2) Додати зв'язки в моделях - коментар належать до статті, стаття (Article) має багато коментарів (аналогічно для автора)`
- [x] Не пуште ніколи закоментований код https://github.com/Haidamac/RubyHW/blob/main/HW6/app/controllers/api/v1/authors_controller.rb#L28-L36
якщо це не підказки чи TODO. Видаліть всі подібні випадки по проекту.
- [x] В контроллерах ArticlesController та CommentsController ви відловлюєте та опрацбовуєте помилки, а от в https://github.com/Haidamac/RubyHW/blob/main/HW6/app/controllers/api/v1/authors_controller.rb чомусь не відловлюєте, потрібно оновити контроллер
- [x] Коли ви використовуєте асоціації, немає потреби викликати метод `.all` https://github.com/Haidamac/RubyHW/blob/main/HW6/app/controllers/api/v1/comments_controller.rb#L11. асоціації за замовчуванням повернуть вам всі записи
- [x] Це варто винести в before_action, щоб не дублювати код
https://github.com/Haidamac/RubyHW/blob/main/HW6/app/controllers/api/v1/authors_controller.rb#L20
https://github.com/Haidamac/RubyHW/blob/main/HW6/app/controllers/api/v1/authors_controller.rb#L10
- [x] В подібних випадках немає потреби пермітити код, ми розповідали на минулому занняті. Також це можна винести в scope
https://github.com/Haidamac/RubyHW/blob/main/HW6/app/controllers/api/v1/comments_controller.rb#L8

**Comment by Haidamac** [comment]
Дякую!!!
Все зробив 
Єдине що - після перевірки рубокопом пофіксив помилки в тому коді, що писав сам, згенерований же при створенні блогу з помилками виявленими рубокопом типу "Missing frozen string literal comment" чи "Use nested module/class definitions instead of compact style.class Api::V1::AuthorsController" наразі пропустив.

**Comment by Kashoid23** [comment]
- [ ] Вам немає сенсу повторно звертатись до асоціації @article.comments, у вас це й так змінній. Подумайте над
```
@comments = @article.comments
@comments = @article.comments.where(status: params[:status]) if params[:status].present?
```
- [ ] Не рекомендуємо проводити будь які маніпуляції над міграціями (з часом ви зрозумієте, що можна робити з нимим вручну, а що ні, але майте на увазі, що це може призвести до помилок в базі данних, які виправити буде дуже складно). Все що стосується змін в базі данних треба робити через міграції.
Наприклад якщо ви мали міграцію, яка створювала таблицю, а вам треба тепере її видалити, то для цього треба створити нову міграцію.
- [ ] Щоб щоразу вручну не оновлювати ід в /db/seeds.rb, їх взагалі не варто вказувати так. Ви можете просто використовувати визначенні змінні, в яких збережено записи
`author_id: author_2.id, article_id: article_5.id`

**Comment by Haidamac** [comment]
Дякую!!!
1 і 4 виправив
питання щодо решти
2. Що Ви маєте на увазі під маніпуляцією над міграціями? Я додав поле в таблицю articles отак:
```ruby
rails g migration add_author_id_to_articles author_id:bigint
```
бо поточна база, з якою працював в HW8 вже не відповідала тим сідам. які прописував для 6ї. Вже потім зрозумів, що простіше було змінити назву бази і заново її закріейтити (ну то зрозуміло, що для тесту, неважливо що там в тій базі є, на практиці не варіант), але вже як є. Як бути, коли є така необхідність, коли в базу треба додавати нові поля? Наче ж після того робив міграції, нічого там не прописував вручну.
3. не зрозумів синтаксис. Я створюю авторів в сідах отак:
```ruby
authors = 5.times do
  Author.create({ name: Faker::ProgrammingLanguage.creator })
end
```
відповідно на ```author_2.id``` і т.п. видає помилку, бо  undefined local variable 
якщо кожного автора створювати окремо типу ```author_1``` ```author_2``` і т.д., то зрозуміло. Але як бути у моєму випадку? Коли для тесту треба багато авторів, багато статей, а ще більше коментів і не раціонально їх прописувати кожну у своїй змінній?

**Comment by Kashoid23** [comment]
2. Я переглядав коміт https://github.com/Haidamac/RubyHW/commit/292c31ed4933671b9530c5262da760cd8741578a
в ньому видалено міграцію `HW6/db/migrate/20221128181751_remove_author_id_from_articles.rb`, от так робити не можна. Бо коли ви або ментори захочете зробити відкат (роллбек) буде помилка. Також ви перейменували там файл міграції `AddAuthorIdToArticles`. Будь що, що ви робити з міграціями не через створення нової міграції призведе в інших помилки (деякі буде дуже важко виправити) в інших, а найгірше, що ви можете зробити -  колись пошкодити незворотньо базу в проді.

3. То був приклад, який наштовхував вас на щось типу

```
5.times do
  author = Author.create({ name: Faker::ProgrammingLanguage.creator })
  article = Article.create({ title: Faker::ProgrammingLanguage.name, body:  Faker::Quote.matz, author_id: author.id })
  Comment.create({ body: Faker::Quote.jack_handey, author_id: author.id, article_id: article.id })
end
```

**Comment by Haidamac** [comment]
Дякую!!!

2. Так, я зрозумів. Справа в тому, що я первісно ще до ДЗ6 додав було додатково поле author_id , потів вирішив, що як в умові цього немає (стосувалося тоді воно лише коментів, а автором статей може бути наприклад тільки власник блогу), то я його і видалив. Коли ж вже в ДЗ8 з'ясувалося, що він таки потрібен, я знову створив це саме поле, але міграція чомусь не пройшла. Я вирішив, що то через той ремув і видалив його, як здається і першу міграцію створення цього поля. Тоді вдалося створити нове поле. Зрозумів, більше так не робитиму :)
3. Дякую, зрозумів!

**Comment by Kashoid23** [comment]
Круто, питайте в разі чого, все окей. Краще один раз обговорити.
