### ISSUE TITLE
RubyHW HW8

### ISSUE THREAD

**Issue by alinajuly** [Haidamac/RubyHW#12]
Хороша робота, маю деякі зауваження:

- [x] добавити downcase або upcase для фільтрації по тегам, так як зараз всі теги прописані великими літерами і якщо прописувати звичайними, то теги не знаходить

- [x]  в респонсі ArticlesController#show мають повертатись поля id, title, body, created_at, author (з іменем автора) для Article та id, body, status, author (з іменем автора) та created_at для коментарів, які належать цьому Article.
Наразі повертаються тільки Articles, без коментарів

- [x] поле status відповідно до завдання має бути для comments, а не Article

**Comment by Haidamac** [comment]
> * в респонсі ArticlesController#show мають повертатись поля id, title, body, created_at, author (з іменем автора) для Article та id, body, status, author (з іменем автора) та created_at для коментарів, які належать цьому Article.
>   Наразі повертаються тільки Articles, без коментарів

Дякую! За запитом http://127.0.0.1:3000/api/v1/articles/:id/ (наприклад http://127.0.0.1:3000/api/v1/articles/1/) повертається саме те, що є в завданні, і що Ви згадали + теги до цієї статті (розширив функціонал на свій розсуд і практики блогінгу). Articles без коментарів повертаються в #index, #search та #order, що відповідає логіці побудови блогу (не перевантажувати блог зайвою інформацією, коли видаються всі статті чи їх частина, що відповідають запиту користувача



> * поле status відповідно до завдання має бути для comments, а не Article

те саме, статус повертається саме для коментарів, дивіться http://127.0.0.1:3000/api/v1/articles/:id/

**Comment by Haidamac** [comment]
> * добавити downcase або upcase для фільтрації по тегам, так як зараз всі теги прописані великими літерами і якщо прописувати звичайними, то теги не знаходить

Дякую за слушне зауваження! Вирішив то за допомогою методу capitalize (позаяк в моїй базі всі теги починаються з заглавної літери)

**Comment by Haidamac** [comment]
Повернувся до Вашого зауваження, щодо методу downcase для фільтрації по тегах. Визнаю, що capitalize є ризиковим методом, його можна застосовувати, лише коли всі абсолютно теги починаються з заглавної, але не містять абревіатур і т.п. штук, наприклад не складаються з 2 слів і інше посинається вже з маленької. Не довіряю в цьому гему Faker, тому в seeds.rb примусово конвертую всі генеровані факером назви тегів downcase і відповідно фільтрація по тегах в articles.rb відбувається з downcase незалежно від того, як назву тегу ввів користувач
