### ISSUE TITLE
Feedback HW10

### ISSUE THREAD

**Issue by bohdanshvec** [Haidamac/RubyHW#14]
I'll be brief, as my assignment is not yet finished.
I have it much worse.
The only thing that seems to me is that the exit from the session has not been worked out.
And I would add the possibility of admin login.

Good job!

**Comment by Haidamac** [comment]
Thank you!
Log out works correctly by click on button in nav bar
Admin login available on http://127.0.0.1:3000/admin  IMHO it no needs on the site
