### ISSUE TITLE
Фідбек ДЗ 9

### ISSUE THREAD

**Issue by Kashoid23** [Haidamac/RubyHW#15]
- [x] Будь ласка додавайте гем рубокоп в проекти та перевіряйте код стайл та форматування з ним. У вас багато з цим проблем. Ми домовлялись ще в ДЗ6. про це
<img width="552" alt="Знімок екрана 2023-01-08 о 11 13 13" src="https://user-images.githubusercontent.com/46579145/211188627-aa534237-d0d3-47b7-8f7d-8b0b43354a1f.png">
Будемо знімати по пів бала за це.

- [x]  Думаю, вже не debugger потрібне https://github.com/Haidamac/RubyHW/blob/main/HW9/spec/requests/api/v1/articles_spec.rb#L9
- [x] let, які не є глобальними, а використовуюються лише в рамках конкретного запиту, наприклад https://github.com/Haidamac/RubyHW/blob/main/HW9/spec/requests/api/v1/articles_spec.rb#L13-L18 варто визначати (перемістити) в блоці response https://github.com/Haidamac/RubyHW/blob/main/HW9/spec/requests/api/v1/articles_spec.rb#L29
Передивіться тести, у вас через раз.
- [x] Після description не потрібно двокрапку, воно не згенерувало це в документації https://github.com/Haidamac/RubyHW/blob/main/HW9/spec/requests/api/v1/comments_spec.rb#L18
- [x] Даний тест перевірить лише статус, але чи створився конкретний Article з данними які ви вказали він не перевіряє https://github.com/Haidamac/RubyHW/blob/main/HW9/spec/requests/api/v1/articles_spec.rb#L54-L62. В відео був приклад (24 стрічка коду в редакторі) https://www.loom.com/share/9b006b2a358c4502b3dfb458bc00e5e3 Те саме по всьому файлові, тест по факту не перевіряє ті данні, які ви вказуєте. Передивіться та оновіть перевірки.
- [x] Вам не треба писати it та describe https://github.com/Haidamac/RubyHW/blob/main/HW9/spec/requests/api/v1/articles_spec.rb#L100-L105 у вас це вже описано. ось цю перевірку https://github.com/Haidamac/RubyHW/blob/main/HW9/spec/requests/api/v1/articles_spec.rb#L103 треба перемістити в блок `run_test! do`, тоді відбудеться перевірки респонса. Ще раз передивіться відео ощ я вам скидав і зверніть увагу на `run_test! do`

**Comment by Kashoid23** [comment]
Круто, що порозписували tags, consumes та parameter. На основі них згенерувалась читабельна документація!

**Comment by Haidamac** [comment]
Дякую!!!

> * Будь ласка додавайте гем рубокоп в проекти та перевіряйте код стайл та форматування з ним. У вас багато з цим проблем. Ми домовлялись ще в ДЗ6. про це
Так, я пам'ятаю про нашу домовленість, та і наче перевіряю всі ДЗ, а тут забув... :( Mea culpa
Зроблю перевірку і рефакторинг по закінченню виправлення інших помилок

У мене проблема з  ```run_test! do```
я правильно зрозумів, що така перевірка потрібна для методів post, put, patch та delete? Для get достатньо перевірки статуса респонса
Я переробив  ```run_test! do``` для згаданих методів в articles_spec.rb
Для put, patch та delete все працює, а от з post проблеми...
Я вже і підключав гем factory_bot_rails, і прописував всі атрибути в let (як в прикладі нижче), і прописав окремо ```       let(:title) { article.title }```, бо конструкція ```expect(data['article']['title']).to eq('...')``` теж не працює...
останній варіант такий:
```ruby
    post('create article') do
      tags 'Article'
      consumes 'application/json'
      parameter name: :article, in: :body, schema: {
        type: :object,
        properties: {
          title: { type: :string },
          body: { type: :string },
          author_id: { type: :integer }
        },
        required: %w[title body author_id]
      }
      response(201, 'successful') do
        let(:author) { create(:author, name: 'Aaaaaaaaaaaa') }
        let(:author_id) { author.id }
        let(:article) { create(:article, title: 'Lorem', body: 'Lorem ipsum', author_id: author_id) }
        let(:id) { article.id }
        let(:title) { article.title }
        after do |example|
          example.metadata[:response][:content] = {
            'application/json' => {
              example: JSON.parse(response.body, symbolize_names: true)
            }
          }
        end
        run_test! do
          data = JSON.parse(response.body)
          expect(data['title']).to eq('Lorem')
        end
      end
    end
```
однак вперто видає помилку 
```expected: "Lorem"
            got: nil```

Коли створюю author і article вручну (під час дебаггінга), все створюється. А автоматично, чомусь nil. Що я роблю не так? 
Зміни запушив

**Comment by Kashoid23** [comment]
Я в відео здається згадував, про `let` і `let!`.
`let!` викликається до виконання тесту (в нашому випадку створив би article чи author).

Додайте дебагер перед  `expect(data['title']).to eq('Lorem')` та перевірте, що в `response` або `response.body`
Також перевірив би чи створено Author.all та Article.all з дебагером

**Comment by Kashoid23** [comment]
А що в response.body? Якщо дебагер додати перед expect(data['title']).to eq('Lorem')

**Comment by Kashoid23** [comment]
`я правильно зрозумів, що така перевірка потрібна для методів post, put, patch та delete?`

В ідеалі тестують все. Наприклад в гет можна перевірити чи повертаються завчасно створені записи, їх id або тайтли.

Ви можете покрити і 2 ендпоінти на ваш вибір, але якщо вам цього дійсно вистачить, щоб розібратись, і коли на екзамені буде питання ви на нього дасте чітку відповідь.

**Comment by Haidamac** [comment]
> А що в response.body? Якщо дебагер додати перед expect(data['title']).to eq('Lorem')

"{\"data\":{\"id\":23,\"title\":\"Lorem\",\"body\":\"Lorem ipsum\",\"created_at\":\"2023-01-08T22:19:34.128Z\",\"updated_at\":\"2023-01-08T22:19:34.128Z\",\"status\":\"unpublished\",\"author_id\":8}}"

> Ви можете покрити і 2 ендпоінти на ваш вибір, але якщо вам цього дійсно вистачить, щоб розібратись, і коли на екзамені буде питання ви на нього дасте чітку відповідь.

дякую! зрозумів! буду розбиратися і з гет

**Comment by Kashoid23** [comment]
В рубі все логічно, просто треба перевіряти команду за командою - дебажити

Якщо response.body виглядає коректно варто в дебагері перевірити попередню команду
`data = JSON.parse(response.body)`

Я от в консолі глянув, може JSON.parse просто повертає nil бо не може розпарсити хеш, здається досить логічним

irb(main):004:0> c = JSON.parse(x)
/Users/everlabs/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/json-2.6.2/lib/json/common.rb:216:in `initialize': no implicit conversion of Hash into String (TypeError)                           
irb(main):005:0> c
=> nil

**Comment by Kashoid23** [comment]
Здається все навіть банальніше. Ви ж повертаєте ключ `data`

Отже в чистому вигляді

```
data = JSON.parse(response.body)
data['data']['title']
```

**Comment by Haidamac** [comment]
Дякую!!!
Так, у випадку з ```expect(data['data']['title']).to eq('Lorem')``` все працює :)
Не зрозумів, де там в тому хеші респонсу взялася data (тоді як за аналогічним кодом у відео мало бути article), ну але зрозумів принцип, як шукати формат коректного запиту :)

**Comment by Haidamac** [comment]
Наче все виконав
Не зрозумів одного:

> * Після description не потрібно двокрапку, воно не згенерувало це в документації

Наче все генерує. Без двокрапки теж генерує, але тоді rubocop свариться :(

**Comment by Kashoid23** [comment]
> Дякую!!! Так, у випадку з `expect(data['data']['title']).to eq('Lorem')` все працює :) Не зрозумів, де там в тому хеші респонсу взялася data (тоді як за аналогічним кодом у відео мало бути article), ну але зрозумів принцип, як шукати формат коректного запиту :)

Думаю так у вас серіалайзер законфіжений, ну або так в ендпоінті ви генеруєте респонс
