### ISSUE TITLE
Feedback HW 11

### ISSUE THREAD

**Issue by bohdanshvec** [Haidamac/RubyHW#16]
Превосходное оформление, мне до такого расти и расти.
НО
То о чём мы говорили, если зайти новым юзером, корзина останется от старого юзера.
И я так и не понял, пытался оплатить ордер, нажимая на красную кнопочку справа внизу unpaid, но статус его так и не менялся.
Метод total_price можно упростить.
Код чистый, красивый.
Хорошая работа.

**Comment by Haidamac** [comment]
Дякую!!!

> То о чём мы говорили, если зайти новым юзером, корзина останется от старого юзера.

Тому що використовуються кукі. АЛЕ, цей баг (якщо це можна назвати багом) існує лише якщо заходити з одного і того ж компа і браузера. На практиці роботи інтернет магазину немає необхідності прив'язувати кожного юзера до корзини, бо природно, що різні юзери використовуватимуть різні точки входу в магазин. Хіба якщо заморочитися. щоб розділити корзини для членів однієї сім'ї, і то у випадку якщо вони використовують один ПК з різними екаунтами, а не заходять з власних телефонів чи ноутів і т.п.. Але як правило такого завдання не стоїть, оскільки корзина - то транзитна функція на шляху до покупки

> И я так и не понял, пытался оплатить ордер, нажимая на красную кнопочку справа внизу unpaid, но статус его так и не менялся.

Оплата ордера відбувається зразу після його створення (та можливості редагування кількості товару чи видалення певних товарних позицій). Крім того я було передбачив ту саму "червону кнопку" для анпейд ордерів, щоб була можливість оплатити їх згодом. Але у цього методу виявився один недолік. Якщо адмін міняв ціну на товар в момент між створенням ордеру і поверненням до його оплати юзером, в ордері ціна залишалася старою. Це ОК для поточної сесії, оскільки не гуд міняти ціну прямо в процесі покупки. Але такий же підхід зберігається і для ордерів, які незавершені і через місяць, скажімо. Думав над вирішенням цієї проблеми, просто перерахувати ціну теж не дуже варіант, тому що дозамовлення ордера ніяк не корелює з наявністю такого товару на даний час на складі (оскільки така опція у нас поки що відсутня, то і городити щось далі немає сенсу).
Поки що повернув дію "червоної кнопки" - відкладений ордер через неї можна завершити - заповнити форму адреси доставки та плетіжні реквізити, тоді і ордер отримує статус "пейд".
На рахунок вирішення проблеми незавершений ордерів маю деякі ідеї інші - зараз ще їх спробую

> Метод total_price можно упростить.

так. дякую!
можна через map, але то вимагатиме іншого додаткового методу, який би рахував збільшення суми відповідно до зміни кількості товару), здалося, що виходить один на один

**Comment by Haidamac** [comment]
Вирішив питання шляхом виділення з unpaid ордерів тих, що створені і незавершені більше 1 доби. Відповідно їх оплатити вже не можна, необхідно створювати новий ордер. Якщо не пізніше доби - ордер можна завершити, вказати адресу доставки і оплатити
