### ISSUE TITLE
HW 11 feedback

### ISSUE THREAD

**Issue by LVALL** [Haidamac/RubyHW#18]
1) Хороший візуал, виглядає досить презентабельно, чудова робота

2) У викликах redirect_to розшляньте можливість використання
```
  flash[:notice] = 'your message'
  redirect_to your_path
```
При використанні notice повідомлення додається безпосередньо до посилання з query param

3) Модель Cart
   3.1 - найменування для зв'язків з many relation потрібно називати в множині, тому не `has_many :line_item, dependent: :nullify` a `has_many :line_items, ...`
   3.2 - модель не є місцем, що повинно відповідати за створення записів, тому метод `add_product` краще винести безпосередньо в контролер/сервіс.

4) Модель LineItem
   4.1 - метод `line_item_total_price` можна назвати просто `total_price`. Так буде значно легше читати код, адже ми завжди викликатимемо даний метод на екземплярі. `line_item.total_price` значно краще, ніж `line_item.line_item_total_price`
   
5) Модель Order
  5.1 - пропоную рефакторинг для методу `order_price`.
  1 - так як ми уже працюємо з ордером, можна пропустити його у назві методу `total_cart_price` підійде краще.
  2 - методи роботи з масивами бажано не використовувати при роботі з вибірками та обрахунками - це значно більше навантажує пам'ять та займає більше часу, ніж та ж операція, виконана ActiveRecord. sum - AR метод
```
def total_cart_price
  cart.line_items.sum('price * quantity')
end
```

6) LineItemsController
  6.1 - у методі `set_line_item` в тілі rescue рендериться json, це означає - що юзер побачить на сторінці лише цей json, коли перейде на неіснуючий елемент. Додайте рендеринг 404 сторінки, або залиште метод без блоку rescue - так в production енвароменті буде відрендерено дефолтну сторінку 404.
  6.2 - можна подумати над тим, щоб об'єднати методи `add_quantity` i `reduce_quantity` в один метод.
  
7) OrdersController
  7.1 - щоб не було потреби перевіряти `if current_user`, при чому коректною була б перевірка `if current_user.present?`, devise надає метод `authenticate_user!`, який ми можемо додати в before filter для тих методів, де нам обов'язкова наявність юзера
  7.2 - def show, як і будь - який з GET реквестів не повинен здійснювати мутацій даних, тобто
```
  if (Time.now > @order.created_at + 1.day) & @order.status == 'unpaid'
      @order.update(status: :canceled)
  ...    
```
   даного фрагменту не повинно бути в методі, подібна логіка виноситься в воркери та сервіси
  7.3 - не зрозумілий підхід до роботи з мейлерами у методі `pay`. Розгляньте можливість прямої передачі аргументів, на заміну використанню інстансів
  ```
  def pay
    @order.update(status: :paid)
    UserMailer.welcome(user_email: current_user.email, order_id: @order.id).deliver_later
    redirect_to order_paid_path, notice: 'Thanks So Much for Your Order! I Hope You Enjoy Your New Purchase!'
  end
  ```

**Comment by Haidamac** [comment]
Дякую!
Зробив рефакторинг по даних зауваженнях
