### ISSUE TITLE
Фідбек ДЗ 2 Тамагочі

### ISSUE THREAD

**Issue by Kashoid23** [Haidamac/RubyHW#2]
В цілому дуже добре. Гра працює. Відповідає умовам задачі.

Було б добре ознайомитись з https://github.com/rubocop/ruby-style-guide або https://rubystyle.guide/#visibility

По апдейтам:

- [x] Перейменуйте будь ласка ім'я файлу `IceAgeTamagotchi.rb`

В рубі, для імені файлів, зазвичай, ми використовуємо lower_snake_case

- [x] Перейменуйте будь ласка імена методів, наприклад `giveFood`

В рубі, для імені метода ми використовуємо lower_snake_case

- [x] Перейменуйте будь ласка імена змінних, наприклад `@lastFeedTime `

В рубі, для імені змінних ми використовуємо lower_snake_case

- [x] Оновіть форматування. Почніть з відступів - це значно поліпшить читабельність коду.

```
Use two spaces per indentation level (aka soft tabs).

# bad - four spaces
def some_method
    do_something
end

# good
def some_method
  do_something
end
```

- [x] Застосуйте `інтерполяцію` для подібних випадків `'Роздратований' + @name + ' вбиває Вас в стані афекту!'`

http://ruby-for-beginners.rubymonstas.org/bonus/string_interpolation.html

Nit:

- [x] Ознайомтесь будь ласка з форматуванням, щоб покращити читабельність Readme

https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

<img width="1228" alt="Screenshot 2022-11-01 at 21 19 19" src="https://user-images.githubusercontent.com/46579145/199320043-8606e01a-a882-44ff-b992-8caae20d10e2.png">

**Comment by Kashoid23** [comment]
По readme, у вас після символів, наприклад #  не вистачає пробілу

**Comment by Haidamac** [comment]
Дякую за зауваження!
Виконав!
