### ISSUE TITLE
Фідбек ДЗ 2 1 завдання

### ISSUE THREAD

**Issue by Kashoid23** [Haidamac/RubyHW#3]
Для перевірки `x%3==0` можна використати метод https://apidock.com/ruby/Numeric/zero%3F

- [x] Зможете в коментарях пояснити що ви тут робите?
`array.select{|x| x < 128}.map{|x| x.chr.match?(/[[:alpha:]]/) ? x.chr : nil}.compact`

- [x] Оновіть рішення за допомогою методів
https://apidock.com/ruby/Enumerable/min
https://apidock.com/ruby/Array/index
https://apidock.com/ruby/Enumerable/max
https://apidock.com/ruby/Enumerable/minmax
https://apidock.com/ruby/Object/clone
Паралельне присвоювання залиште

```
array_res=array
array_res[array_res.each_with_index.min[1]],array_res[array_res.each_with_index.max[1]]=array_res[array_res.each_with_index.max[1]],array_res[array_res.each_with_index.min[1]]
```

**Comment by Haidamac** [comment]
Дякую! Щодо пояснення:

> Зможете в коментарях пояснити що ви тут робите?
array.select{|x| x < 128}.map{|x| x.chr.match?(/[[:alpha:]]/) ? x.chr : nil}.compact

Наскільки зрозумів умову завдання, замість елементів масиву треба вивести латинські літери, яким відповідає ANSCII-код. Оскільки таких символів в таблиці ANSCII від 0 до 127, select'ом я просто відсік решту елементів (все що більше 127). Далі за допомогою map я будую новий масив, в якому за допомогою поєднання методів chr.match? перевіряю, чи символ, якому відповідає порядковий номер з первісного масиву в ANSCII таблиці є літерою. Якщо так - додаю в новий масив цю літеру, якщо ні - nil. Потім всі nil'и відсікаю методом compact

**Comment by Kashoid23** [comment]
Насправді ви ускладнили собі задачу
В умові не йшлось про ANSCII
`отримати новий масив, який би містив в собі ті літери англійського алфавіту, порядковий номер яких є в нашому масиві`
Я вважаю, що з ANSCII порядкові номери не збігаються, спробуйте діапазон літер ('a'..'z') - це в вузькому розумінні представлення для літер англійського алфавіту.

Плюс, за те що ви розібрались з методами які застосували.

**Comment by Haidamac** [comment]
А, зрозумів.
Тоді якось так:
p array.map{|x| x <27 ? ('a'..'z').to_a[x] : nil}.compact

**Comment by Haidamac** [comment]
> * Оновіть рішення за допомогою методів
>   https://apidock.com/ruby/Enumerable/min
>   https://apidock.com/ruby/Array/index
>   https://apidock.com/ruby/Enumerable/max
>   https://apidock.com/ruby/Enumerable/minmax
>   https://apidock.com/ruby/Object/clone
>   Паралельне присвоювання залиште

Зробив: 
ar_res = array.clone
ar_res[ar_res.index(ar_res.min)], ar_res[ar_res.index(ar_res.max)] = ar_res[ar_res.index(ar_res.max)], ar_res[ar_res.index(ar_res.min)]
p ar_res

**Comment by Kashoid23** [comment]
Супер, а де тут застосувати https://apidock.com/ruby/Enumerable/minmax не розібрались?

**Comment by Haidamac** [comment]
та щось ніяк не придумав. куди його притулити. Метод видає масив з двох елементів, мінімального та максимального, що далі з цим робити, ніяк не розумію :)

**Comment by Kashoid23** [comment]
А ви подумайте )

Що повертає права частина вашого паралельного присвоювання

`= ar_res[ar_res.index(ar_res.max)], ar_res[ar_res.index(ar_res.min)]`

**Comment by Haidamac** [comment]
тоді отак от :)

ar_res = array.clone
ar_res[ar_res.index(ar_res.min)], ar_res[ar_res.index(ar_res.max)] = ar_res.minmax.reverse
p ar_res

ну або навпаки

ar_res[ar_res.index(ar_res.max)], ar_res[ar_res.index(ar_res.min)] = ar_res.minmax

**Comment by Kashoid23** [comment]
Другий варіант саме те чого
