### ISSUE TITLE
Feedback HW3 Tamagotchi with html gem

### ISSUE THREAD

**Issue by alinajuly** [Haidamac/RubyHW#4]
- [x] За умовою завдання сторінка html має формуватися кожного разу після дії з вихованцем, а у вас вона тільки викликається за бажанням. Модифікуйте код до умови завдання.

- [x] Код прописаний для операційної системи Windows через system("start index.html"), тому на Ubuntu не формує html сторінку. Можливо, треба використати гем для визначення ОС.

- [x] Метод def html не відноситья до класу STsquirrel, треба винести його за межі класу.

**Comment by Haidamac** [comment]
Thank you!

> * Код прописаний для операційної системи Windows через system("start index.html"), тому на Ubuntu не формує html сторінку. Можливо, треба використати гем для визначення ОС.

Resolved with os gem [https://rubygems.org/gems/os](https://rubygems.org/gems/os)

**Comment by Haidamac** [comment]
> * За умовою завдання сторінка html має формуватися кожного разу після дії з вихованцем, а у вас вона тільки викликається за бажанням. Модифікуйте код до умови завдання.

Resolved!

**Comment by Haidamac** [comment]
> * [x]  Метод def html не відноситья до класу STsquirrel, треба винести його за межі класу.
Thank you!
I split the file into two parts, moved the method to another class
