### ISSUE TITLE
Feedback Tamago HW3

### ISSUE THREAD

**Issue by LVALL** [Haidamac/RubyHW#5]
- [x] дублювання коду
```
      @health       -= 3
      @big_acorn     = 0
      @mood         -= 2
      @irritability += 3
      passage_of_time
```
даний фрагмент повторюється більше двох разів, але з різними числами. Спробуйте винести в окремий метод цей та інші моменти дублювання у коді. Для того, щоб значення не були однаковими, можна використати метод `rand`

- [x] метод [html](https://github.com/Haidamac/RubyHW/blob/dedf5afb336e7b3e02b4a04af63be55643ad1734/HW3/iat.rb#L89) надто великий та логічно не повинен бути частиною класу тваринки. Пропоную винести даний метод в окремий клас. Також в той же окремий клас можна винести метод взаємодії з тваринкою.

- [x] повертаючись до попереднього пункту, стосовно розміру методу, та використання конструкцій `if`. Таке їх скупчення ускладнює читабельність коду.

В якості варіанту вирішення, як мінімум варто розбити на окремі приватні методи в межах класу, в який буде винесено метод `html` буде щось типу:

```
def set_emojies
  @health_em = health_emojies
  # set more from youur emojies here
end

private
  def health_emojies
    if @health <= 10 && @health >= 0
      "&#128522;" * @health + "&#129397;" * (10 - @health)
    elsif @health < 0
      "&#129397;" * 10
    else
      "&#128522;" * 10
    end
  end
```

альтернативою для повторюваниї `if elsif else` стейтментів може бути щось на зразок цього коду:

```
  def health_emojies
    combinated_emojies = "&#128522;" * @health + "&#129397;" * (10 - @health)
    return combinated_emojies  if @health.between?(0, 10)
   
    emoji = health.negative? ? "&#129397;" : "&#128522;"
    emoji  * 10
  end
```

- [x] не забувайте про можливість використання `attribute_reader`

**Comment by Haidamac** [comment]
Дякую!
1) Дублювання коду воніс в метод outcome
Принагідно створив ще і метод revival для уникнення повторення коду нижче
2) Розділив файл програми на 2, метод html виніс за межі класу Pet

єдине, що не вийшло
змінні, що генеруються у цьому пропонованому класі:

```ruby
def set_emojies
  @health_em = health_emojies
  # і так далі
end
```
вперто повертають nil
згенерував html не через ці змінні, а просто через створені методи life_emojies і т.д.
конструкцію if elsif else змінив на пропоновану
