### ISSUE TITLE
Feedback HW4

### ISSUE THREAD

**Issue by MaksHostroushko** [Haidamac/RubyHW#6]
Looks great!
Let's add some improvements

1. For now, it's possible to create a Pet without a name(just with blanks). Please, check if a string is empty
2. Please, improve README. First of all, it should display a path of your project, not of some other folders/files
3. If you have authorization - let's write some credentials in README. It's not the best way to search it in config files
4. Please, refactor your code according to the [code style](https://github.com/rubocop/ruby-style-guide). You have a lot of incorrect spaces!
5. `passage_of_time if @irritability >9 || @mood < 1` 
Try to don't use a single line if the condition includes more the 1 condition
6. Don't forget about using `else` for `case`
https://github.com/Haidamac/RubyHW/blob/main/HW4/pet.rb#L179..L208
7. Try to don't use nested `if/else` conditions

**Comment by Haidamac** [comment]
Thank you for review and suggestions!!!

1. Resolved via  
```ruby
name.delete(' ').length.zero?
```
2-3. README.md is improved according to remarks
4. Fixed!
5. Fixed:
```ruby
if @irritability >9 || @mood < 1
  passage_of_time 
end
```
6. Resolved by changing  ```when 0, 2, 4, 8``` with ```else```
7. Fixed
