### ISSUE TITLE
Отзыв на работу HW5

### ISSUE THREAD

**Issue by fillson22** [Haidamac/RubyHW#7]
Привет. Хорошая работа.

- Всегда приятно когда написан корректный readme.md
- Все пункты readme прошли успешно.
- Api-шка работает нормально, все экшены выполняют свою функцию.
- Код читабельный с наличием комментов.

В общем, хорошая работа, почерпнул несколько моментов и для себя.

**Comment by Haidamac** [comment]
Thank you!
