### ISSUE TITLE
Feedback HW5

### ISSUE THREAD

**Issue by Kashoid23** [Haidamac/RubyHW#8]
Дуже хороша ідея з Readme!
Круто, що є [db/seeds.rb](https://github.com/Haidamac/RubyHW/tree/main/HW5/db/seeds.rb)

- [x] Спробуйте передивитись список http://www.railsstatuscodes.com/ та використати коректні статуси для ваших респонсів
Наприклад
`render json: { message: "Not found" }, status: :bad_request`
Коли ви відправляєте статус, він вже включає стандартне повідомлення, тому якщо ви НЕ хочете повертати якесь кастомне (що не відповідатиме стандартному) повідомлення, його не потрібно додатково прописувати

Також зверніть увагу, що повідомлення `Not found` і статус `bad_request`, що вводить в оману.
Тобто респонс мав би виглядати приблизно так
`render status: :bad_request`
https://guides.rubyonrails.org/layouts_and_rendering.html#the-status-option

- [x] Підозруюю це https://github.com/Haidamac/RubyHW/blob/main/HW5/app/controllers/api/v1/articles_controller.rb#L19 мав бути статус, а не `state: :ok` 
Для цікавості що передається в `render` https://guides.rubyonrails.org/layouts_and_rendering.html#using-render

- [x] З приводу Not found, якщо не знайде - запис тут не все так однозначно.
https://github.com/Haidamac/RubyHW/blob/main/HW5/app/controllers/api/v1/articles_controller.rb#L17 
Метод find не такий простий https://apidock.com/rails/ActiveRecord/FinderMethods/find він за замовчуванням райзить https://www.geeksforgeeks.org/raising-exceptions-in-ruby/ помилку і якщо ви дійсно хочете її обробляти то це буде не так просто, ось приклади http://rubyjunky.com/never-check-for-an-error-you-dont-know-how-to-handle.html

- [x] Зверніть увагу на приватний метод set_article https://github.com/Haidamac/RubyHW/blob/main/HW5/app/controllers/api/v1/articles_controller.rb#L58, який в цьому контроллері використовується в ролі колбека для фільтрів https://guides.rubyonrails.org/action_controller_overview.html#filters та буде заміняти дублювання коду в трьох місцях `@article = Article.find(params[:id])`

Ось як це працює
https://dannemanne.com/posts/ruby_on_rails_explained_before_action

- [x] Почитайте про контроллери https://guides.rubyonrails.org/action_controller_overview.html

**Comment by Haidamac** [comment]
Дякую!!!

>  Спробуйте передивитись список http://www.railsstatuscodes.com/ та використати коректні статуси для ваших респонсів

Щодо респонсів зрозумів, постарався виправити
 
> Підозруюю це https://github.com/Haidamac/RubyHW/blob/main/HW5/app/controllers/api/v1/articles_controller.rb#L19 мав бути статус, а не `state: :ok`

Так, це одрук, сам знайшов при роботі над HW6, забув поміняти

> З приводу Not found, якщо не знайде - запис тут не все так однозначно.

Дякую! Скористався посиланням, прописав в приватному методі ```set_article```:
```ruby
rescue ActiveRecord::RecordNotFound => e
   logger.info e
   return render json: { message: 'article id not found' }, status: :not_found
```
Тепер при помилці спроби пошуку неіснуючого id обробляє помилку і видає кастомне повідомлення

> Зверніть увагу на приватний метод set_article 

використав метод для уникнення дублювання коду в ```show```, ```update``` та ```destroy```

**Comment by Kashoid23** [comment]
У вас була можливість перечитати усі посилання? )

Підказка
Ви додали виклик set_article в show, update та destroy
А що тоді робить ваш before_action :set_article?

**Comment by Haidamac** [comment]
Ой, точно :)
```before_action :set_article``` спершу виконала той приватний метод і змінна ```@article``` вже визначена, то ж у цих трьох методах show, update та destroy її перевизначати немає потреби :)

**Comment by Kashoid23** [comment]
Супер )

Спробуйте ще й підключити гем рубокоп

https://github.com/rubocop/rubocop

Він допоможе з форматуванням та підкаже де ще помилки незначні )

Ось тут про нього почитайте
https://semaphoreci.com/blog/rubocop
